### ISSUE TITLE
Issue Android 5.0 Lg LEON

### ISSUE THREAD

**Issue by FunnyDevs** [CherryPerry/VideoCrop#2]
I'm using your code but i have a problem with this kind of smartphone when configure the video encoder
The error is this

> 12-20 13:11:49.410 5781-5817/ I/OMXClient: Treble IOmx obtained
> 12-20 13:11:49.423 5781-5817/ E/ACodec: [OMX.google.h264.encoder] configureCodec returning error -38
> 12-20 13:11:49.424 5781-5817/ E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
> 12-20 13:11:49.424 5781-5816/ E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 3
> 12-20 13:11:49.425 5781-5801/ E/MediaCodec: configure failed with err 0x80001001, resetting...
> 12-20 13:11:49.433 5781-5817/com.humaneyes.filesave I/OMXClient: Treble IOmx obtained

So i have removed this line from MediaCodefFactory

> mediaFormat.setInteger(MediaFormat.KEY_PROFILE, MediaCodecInfo.CodecProfileLevel.AVCProfileBaseline)

The encoder was created but then the code stucks on this line

>  while (decoderOutputIndex == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED
>                 || decoderOutputIndex == MediaCodec.INFO_OUTPUT_BUFFERS_CHANGED) {
>                 decoderOutputIndex = decoder.dequeueOutputBufferInfinite(bufferInfo)
>             }

**Comment by CherryPerry** [comment]
Does it stuck in cycle or just on line ```dequeueOutputBufferInfinite```?
Anyway I don't know why, code is unstable, don't work on emulator too.

**Comment by FunnyDevs** [comment]
It stucks on first
> dequeueOutputBufferInfinite
inside the while

**Comment by CherryPerry** [comment]
@FunnyDevs can you check latest repository version https://github.com/CherryPerry/VideoCrop/commit/fdd934ea3c8c302df66e97317f3b8d5371f4ea1a?

**Comment by FunnyDevs** [comment]
not yet, i'll try it in the next few days
