### ISSUE TITLE
How to add multiple timelines for multiple videos selected

### ISSUE THREAD

**Issue by mdzafar3194** [CherryPerry/VideoCrop#6]
Please help me out in achieving multiple Timelines, where to display the frames of selected videos

**Reference Image**
![image](https://user-images.githubusercontent.com/22235737/62530498-4d032880-b85e-11e9-86e1-997fa97c1ba0.png)

Here, in the screenshot have used three Timelines and with a horizontal scroll to view the frames of all three timelines at a time.
Plus icon is used to select Video/Image from Phone gallery. Selected media will appear in respective timelines

**Comment by CherryPerry** [comment]
If videos have same frame rate, then you can decode both of videos to bitmap frames and do any transformation you want.
But because you need to show it in realtime, my solution won't work. You probably need to go deeper inside framework and probably implement your own `ExoPlayer`'s  `MediaSource`.

**Comment by mdzafar3194** [comment]
@CherryPerry, Okay thanks
And if you know any related github projects for my reference to achieve same as above shared image.
It will help very helpful for me and will be thankful to you.

**Comment by CherryPerry** [comment]
No, I don't know such projects.
